apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: securesign-pipelines-demo
resources:
  - verify-source-el-route.yaml
  - verify-source-el.yaml
  - verify-commit-signature-task.yaml
  - verify-source-code-pipeline.yaml
  - verify-source-code-triggertemplate.yaml
